export const DRAWING_ACTION_ADD_ITEM = 'DRAWING_ACTION_ADD_ITEM';

export const DRAWING_ACTION_REMOVE_ITEM = 'DRAWING_ACTION_REMOVE_ITEM';

export type DrawingAction = typeof DRAWING_ACTION_ADD_ITEM | typeof DRAWING_ACTION_REMOVE_ITEM;

export const DRAWING_ITEM_WALL = 'DRAWING_ITEM_WALL';

export const DRAWING_ITEM_DESERT = 'DRAWING_ITEM_DESERT';

export type DrawingItem = typeof DRAWING_ITEM_WALL | typeof DRAWING_ITEM_DESERT;
